apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: xline
  namespace: kube-system
spec:
  containers:
    - name: xline
      image: ghcr.io/xline-kv/xline:v0.6.0
      imagePullPolicy: IfNotPresent
      env:
      - name: RUST_LOG
        value: debug
      command:
        - /bin/sh
        - -c
        - xline --name node1 --members node1=172.18.0.2:2379 --data-dir /tmp/xline --storage-engine rocksdb
  hostNetwork: true
status: {}