apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: xline2
  namespace: kube-system
spec:
  containers:
    - name: xline
      image: ghcr.io/xline-kv/xline:master
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - xline --name node1 --members node1=kind-control-plane:2379,node2=kind-control-plane:2479,node3=kind-control-plane:2579 --data-dir /tmp/xline --storage-engine rocksdb --client-listen-urls=http://kind-control-plane:2479 --peer-listen-urls=http://kind-control-plane:2480,http://kind-control-plane:2481 --client-advertise-urls=http://kind-control-plane:2479 --peer-advertise-urls=http://kind-control-plane:2480,http://kind-control-plane:2481
  hostNetwork: true
status: {}
