kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: ghcr.io/xline-kv/kind-node-xline:${K8S_VERSION}-master
  extraMounts:
    - hostPath: ${WORKSPACE}/ci/artifacts/multe-node/000-xline.yaml
      containerPath: /etc/kubernetes/manifests/000-xline.yaml
    - hostPath: ${WORKSPACE}/ci/artifacts/multe-node/001-xline.yaml
      containerPath: /etc/kubernetes/manifests/001-xline.yaml
    - hostPath: ${WORKSPACE}/ci/artifacts/multe-node/002-xline.yaml
      containerPath: /etc/kubernetes/manifests/002-xline.yaml
  kubeadmConfigPatches:
    - |
      kind: ClusterConfiguration
      etcd:
        external:
          endpoints:
          - http://kind-control-plane:2379
          - http://kind-control-plane:2479
          - http://kind-control-plane:2579
- role: worker
  image: ghcr.io/xline-kv/kind-node-xline:${K8S_VERSION}-master
- role: worker
  image: ghcr.io/xline-kv/kind-node-xline:${K8S_VERSION}-master
