name: Docker

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
  push:

env:
  CI_RUST_TOOLCHAIN: 1.70.0

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo bash ./.github/scripts/install_deps.sh
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ env.CI_RUST_TOOLCHAIN }}
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run: |
          mv ./target/release/xline ./scripts
          mv ./target/release/benchmark ./scripts
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
#      - name: Generate App Version
#        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      - name: Set APP Version to latest
        if: github.event.name == 'schedule'
        run: echo APP_VERSION="latest" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./scripts
          tags: |
            ghcr.io/liangyuanpeng/xline:latest
            ghcr.io/liangyuanpeng/xline:${{ env.APP_VERSION }}
